### ISSUE TITLE
Building on Linux on ARM64

### ISSUE THREAD

**Issue by a13xie** [OpenPathGuidingLibrary/openpgl#6]
Is aarch64 Linux ever going to be supported like with Embree? Or is it never going to happen like with [OpenImageDenoise](https://github.com/OpenImageDenoise/oidn/issues/125)?

Right now building openpgl on ARM fails. I have attached the error.
[build.log](https://github.com/OpenPathGuidingLibrary/openpgl/files/10798667/build.log)

**Comment by sherholz-intel** [comment]
@a13xie could you give us a little bit more information of your arm-based system?

**Comment by StefanBruens** [comment]
You are apparently affected by https://github.com/embree/embree/issues/410

TLDR: add "-flax-vector-conversions" to your CXXFLAGS

**Comment by a13xie** [comment]
@StefanBruens Thank you so much! Indeed using `-flax-vector-conversions` while building OPGL seems to fix this.

Should I close the issue?

**Comment by sherholz-intel** [comment]
@a13xie wait with the closing for the next point release.
I will add this flag with some others.

**Comment by sherholz-intel** [comment]
@StefanBruens thanks for looking up a fix and pointing it out.

**Comment by sherholz-intel** [comment]
Hi @a13xie ,

could you try and see if the ``fix/linux-arm-and-visibility`` branch fixes your problem?

**Comment by a13xie** [comment]
> Hi @a13xie ,
> 
> could you try and see if the ``fix/linux-arm-and-visibility`` branch fixes your problem?
>  

Will do!

**Comment by a13xie** [comment]
@sherholz-intel I can confirm that building from the `fix/linux-arm-and-visibility` branch doesn't require manually adding the `-flax-vector-conversions` flag anymore.

**Comment by sherholz-intel** [comment]
Thanks for testing. This fix will be included in the next release.
